### ISSUE TITLE
Too many queries issued for "cm new"

### ISSUE THREAD

**Issue by strk** [tamentis/cartman#14]
Adding debugging lines I see three GET requests being performed _before_ starting the editor:
```
Getting /login
Getting /
Getting /query?max=1&order=priority
```

NOTE: the third one is modified as per #12 to reduce the size of returned page.

I understand the first one (which would ideally be avoided by storing cookies offline, see #13),
but what's the second one for ?

**Comment by tamentis** [comment]
It's currently done as part of `login()` in order to "Load a page to get the new cookies". It might not be required on all Trac versions or even all authentication types.

**Comment by strk** [comment]
How about just checking if the "trac_auth" cookie exists after the first call ? I see the setCookie header sent in response to the /login action already.

**Comment by tamentis** [comment]
I dropped that get("/") in my sandbox without any issues, I'll try at work, we use a reverse-proxy for auth, if that works fine then we should be able to drop it.

**Comment by strk** [comment]
Dropping the get("/") worked for me too, against trac 1.0.5

**Comment by tamentis** [comment]
I pushed the removal of that extra get.
