### ISSUE TITLE
Update web site and changes file for 0.3.0 release

### ISSUE THREAD

**Issue by ryandesign** [tamentis/cartman#32]
PyPi and the Releases tab of this repository show that version 0.3.0 was released on March 14, 2020, but CHANGES.txt does not include the release date for 0.3.0 and since it was last updated years ago I'm not sure whether it mentions every change that went into 0.3.0. The [https://tamentis.com/projects/cartman/ web site] still says the latest version is 0.2.3 and should be updated.

**Comment by ryandesign** [comment]
Actually I see that within the v0.3.0 tag, CHANGES.txt has been updated, but on master it has not. So I'm not sure what happened there but I guess any changes that were made in the tag but not in master should be copied to master.

**Comment by tamentis** [comment]
I think I forgot to push :|

I updated everything, thanks for reporting.
