### ISSUE TITLE
comment: error: unable to fetch timestamp -- WARNING: Untested Trac version (1.4)

### ISSUE THREAD

**Issue by strk** [tamentis/cartman#36]
I cannot comment on a ticket with Trac version 1.4, this is what happens:
```
WARNING: Untested Trac version (1.4)
error: unable to fetch timestamp
```

**Comment by strk** [comment]
The target trac instance is trac.osgeo.org - if it helps testing

**Comment by strk** [comment]
Reading the code it looks like this bug is not related to trac version but rather to some kind of theme. This is because Cartman looks for a `start_time` string in the HTML, and I DO see that string here: https://trac.edgewall.org/ticket/8813 while I dont' see it here: https://trac.osgeo.org/osgeo/ticket/2759

In both pages I do find a `Powered By Trac 1.4.3` so the difference is elsewhere (custom theme?)

**Comment by MFreeze** [comment]
It's been a while now, but you can solve the problem by replacing:

```python
    regex = r"""name="{}" value="([^"]+)""".format(token)
```
in `text.extract_timestamps_common` by

```python
    regex = r"""name="{}"\s*value="([^"]+)""".format(token)
```

**Comment by strk** [comment]
Thanks, that works. PR ready #37
