### ISSUE TITLE
error: unable to get an EDITOR environment variable

### ISSUE THREAD

**Issue by strk** [tamentis/cartman#8]
~/.cartman/config presence of an "editor" variable does not prevent the error from occurring on "cm new"

**Comment by tamentis** [comment]
What OS? I can't reproduce that issue with an empty/missing `EDITOR` variable. Can you share the config file (minus your credentials) and maybe your env. I tried deleting the `EDITOR` environment variable but I don't get an error, unless editor is missing from the configuration file as well.

**Comment by strk** [comment]
Ubuntu 14.04.3 LTS, no "editor" in config file results
in the error, no matter exporting an EDITOR variable.

There's no much to see in the configuration file, as the issue
here is being unable to _avoid_ writing an "editor" variable in there.

**Comment by tamentis** [comment]
Ok, so you have an exported EDITOR variable in your environment and nothing in your cartman config.

I literally have the same setup and it works fine here, what do you have if you type the following in a python interpreter:
```
>>> import os
>>> os.getenv("EDITOR")
```

**Comment by strk** [comment]
Never mind, it looks like I cannot reproduce this anymore,
it's working fine. Not sure what I stepped on before.
This can be closed.

**Comment by tamentis** [comment]
Thanks for confirming.
